kind: Service
apiVersion: v1
metadata:
  name: spark-ui-proxy
  namespace: spark-cluster
spec:
  type: ClusterIP
  clusterIP: 10.91.250.10
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: spark-ui-proxy