kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker
  namespace: spark-cluster
spec:
  replicas: 1
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: preemptible-pool
      containers:
        - name: spark-worker
          image: gcr.io/sqhive-backend/spark-worker
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
              memory: 1Gi