kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller
  namespace: spark-cluster
spec:
  replicas: 1
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: apache/zeppelin:0.7.3
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
          env:
            - name: SPARK_MASTER
              value: "spark://spark-master:7077"
            - name: ZEPPELIN_PORT
              value: 8080
            - name: ZEPPELIN_LOG_DIR
              value: "/logs"
            - name: ZEPPELIN_NOTEBOOK_DIR
              value: "/notebook"
          volumeMounts:
            - mountPath: /logs
              name: zeppelin-logs
            - mountPath: /notebook
              name: zeppelin-notebook
      volumes:
        - name: zeppelin-logs
          persistentVolumeClaim:
            claimName: nfs-zeppelin-logs
        - name: zeppelin-notebook
          persistentVolumeClaim:
            claimName: nfs-zeppelin-notebook
